AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.1

Metrics:
  Enabled: false

# TODO

Style/Documentation:
  Exclude:
    - 'lib/credit_card_sanitizer.rb'

# Configured

# Layout

Layout/CaseIndentation:
  EnforcedStyle: end
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/FirstParameterIndentation:
  EnforcedStyle: consistent
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

# Allow ▇  in comments
Style/AsciiComments:
  Exclude:
    - 'lib/credit_card_sanitizer.rb'

# Lint

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

# Disabled

# Layout

Layout/LineLength:
  Enabled: false

# Lint

Lint/AssignmentInCondition:
  Enabled: false

# Style

Style/DoubleNegation:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
Style/StringConcatenation:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/WordArray:
  Enabled: false
